### ISSUE TITLE
Question how to use the tool

### ISSUE THREAD

**Issue by ansou2020** [nickrod518/Migrate-WindowsUserProfile#31]
Hello Nick,

Thanks for you reply

- I am running the script directly from PS ISE, when i click run i get this error
**(https://user-images.githubusercontent.com/45219296/48847700-2b195280-ed70-11e8-80db-19c389a4b838.png)** this error results upon clicking run in PS ISE.

then the tool is already opens, in the old computer tab, my local machine is set as the old the computer, and i can enter my new computer name no problem with IP, the connection is establsihed

![issue2](https://user-images.githubusercontent.com/45219296/48847849-8ba88f80-ed70-11e8-8258-d2e5b889bff8.png)

The migration succeeds with no issue, the data is stored in the default location of the new computer.

The problem i have is when i go to the new computer tab, the computer that was set as old computer from the old computer tab is now set as the new computer and old computer in the new computer tab. 

How do i migrate to the new computer from the new computer tab? How do i make sure the info in the new computer tab is correct and reflect from the info i put in the old computer?

Do i need to run this script in PS ISEor i how should i call the invoke-usmtgui.ps1?
![issue3](https://user-images.githubusercontent.com/45219296/48848251-74b66d00-ed71-11e8-8bdc-e49082ce836f.png)

**Comment by nickrod518** [comment]
Adding my email replies for record:

The computer info section on the new computer tab is only necessary if you're running the tool on both computers at once. If you set the details properly, the new computer will detect that the migration has finished on the old computer and immediately start importing on the new computer. If you're doing the computers one step at a time (sounds like this is your case) then when you launch the tool on the new computer and you're on the new computer tab you should check the box that says "save state task complete". This means that you've already got your migration data saved on the new computer and you're ready to import. By checking that box, the Computer Info section is discarded. I hope that clears things up.

As far as launching directly or via ISE, I actually prefer creating a self-extracting zip because then everything is bundled into one portable exe that you can launch. I actually have another project that makes this easy - https://github.com/nickrod518/Create-EXEFromPS1. Otherwise, I'd go for the script directly and avoid the ISE. Sometimes the ISE can introduce weird problems.

The GUI sticks around even after the migration completes. This is so you can inspect the log if you want. Is that what you're saying is sticking around, or are you saying the USMT cmd window that is invoked sticks around?

What I mean by "running the tool on both computers at once" is that you launch the tool on the new computer and begin the migration. While it is running (it must invoke the USMT cmd window or this won't work properly) you launch the tool on the new computer and fill out the computer info; enter the hostname or ip address of the old computer. What happens is on the new computer the tool will monitor the processes running on the old computer to try and see when the USMT process has completed and automatically begin importing. It's just a feature so that if you don't have both computers physically in front of you, or you plan on stepping away for a while, you can have a little convenience in knowing the process on the new computer will kick off as soon as possible.

I hope this answers your questions and let me know if you have more.

Nick
